include:
  - project: 'tailscale-dev/gitops-acl-ci'
    ref: main
    file: 'acls.gitlab-ci.yaml'
    with:
      api-key: tskey-auth-kB3xkTw4qh11CNTRL-7iejFti5ZmFa8mq6C7dHnFRNYNPjy5CYN
      tailnet: tskey-api-kQBugEm2EP11CNTRL-HUShQTHQTuMnX56J3Rp3uM4osojTXRY75

stages:
  - test
  - apply

test:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'

apply:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
